/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author nanua
 */
public class Balance_Enquiry extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Balance_Enquiry
     */
    public Balance_Enquiry() {
        initComponents();
    }
    JButton exit11;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img5.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 810));
        JLabel text7 =new JLabel("Your Current Amount is:");
        text7.setFont(new Font("System",Font.BOLD,24));
        text7.setForeground(Color.WHITE);
        text7.setBounds(235,310,300,30);
        img5.add(text7);
        JLabel text9 =new JLabel("==> Rs.");
        text9.setFont(new Font("System",Font.BOLD,24));
        text9.setForeground(Color.WHITE);
        text9.setBounds(235,340,100,30);
        img5.add(text9);
        JLabel text1 =new JLabel("10005685679854533545");
        text1.setFont(new Font("System",Font.BOLD,24));
        text1.setBackground(Color.BLUE);
        text1.setForeground(Color.WHITE);
        text1.setBounds(320,340,400,30);
        img5.add(text1);
        exit11 =new JButton("Exit");
        exit11.setBounds(565,520,125,35);
        exit11.addActionListener(this);
        img5.add(exit11);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit11){
//                System.exit(0);
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance_Enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance_Enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance_Enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance_Enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balance_Enquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
