/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author nanua
 */
public class Deposit extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
    }
    JButton next,exit;
    JTextField text1;
    int money;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 810));
        JLabel text =new JLabel("Enter Amount you want to Deposit:");
        text.setFont(new Font("System",Font.BOLD,24));
        text.setForeground(Color.WHITE);
        text.setBounds(235,310,450,30);
        img1.add(text);
        JTextField text1 =new JTextField();
        text1.setFont(new Font("System",Font.BOLD,24));
        text1.setBackground(Color.WHITE);
        text1.setForeground(Color.BLACK);
        text1.setBounds(235,345,150,30);
        img1.add(text1);

        next =new JButton("Next");
        next.setBounds(195,515,125,35);
        next.addActionListener(this);
        img1.add(next);
        exit =new JButton("Exit");
        exit.setBounds(565,515,125,35);
        exit.addActionListener(this);
        img1.add(exit);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    String getmoney=text1.getText();
    void _deposit(){
        money=5000;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
    
            String sql ="select * from signupaccount where current=?";
            Statement st=con.createStatement();
//            int i=st.executeUpdate();
//            if(int i>0){
//                JOptionPane.showMessageDialog(this,"Your amount deposited successfully.");
//            }
//            else{
//                System.out.println("Error occured");
//            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit){
//                System.exit(0);
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }else if(ae.getSource()==next){
//                _deposit();
                JOptionPane.showMessageDialog(this,"deposit");
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
