/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author nanua
 */
public class FastCash extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FastCash
     */
    public FastCash() {
        initComponents();
    }
    JButton tenk,fiveh,twok,onek,fivek,fifteenk,exit7;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img7.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage.png")); // NOI18N
        getContentPane().add(img7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 890));
        JLabel text =new JLabel("Select withdrawl amount");
        text.setFont(new Font("System",Font.BOLD,16));
        text.setForeground(Color.WHITE);
        text.setBounds(175,340,300,30);
        img7.add(text);
        fiveh =new JButton("500");
        fiveh.setBounds(145,405,120,30);
        fiveh.addActionListener(this);
        img7.add(fiveh);
        twok =new JButton("2000");
        twok.setBounds(145,445,120,30);
        twok.addActionListener(this);
        img7.add(twok);
        fivek =new JButton("5000");
        fivek.setBounds(145,485,120,30);
        fivek.addActionListener(this);
        img7.add(fivek);
        onek =new JButton("1000");
        onek.setBounds(335,405,120,30);
        onek.addActionListener(this);
        img7.add(onek);
        tenk =new JButton("10000");
        tenk.setBounds(335,445,120,30);
        tenk.addActionListener(this);
        img7.add(tenk);
        fifteenk =new JButton("15000");
        fifteenk.setBounds(335,485,120,30);
        fifteenk.addActionListener(this);
        img7.add(fifteenk);
        exit7 =new JButton("Exit");
        exit7.setBounds(335,525,120,30);
        exit7.addActionListener(this);
        img7.add(exit7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit7){
//                System.exit(0);
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
