/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author nanua
 */
public class PinChange extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form PinChange
     */
    public PinChange() {
        initComponents();
    }
    JButton exit6,next6;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img4.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage.png")); // NOI18N
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 890));
        JLabel text =new JLabel("Reset PIN");
        text.setFont(new Font("System",Font.BOLD,16));
        text.setForeground(Color.WHITE);
        text.setBounds(175,340,300,30);
        img4.add(text);
        JLabel text1 =new JLabel("PIN");
        text1.setFont(new Font("System",Font.BOLD,12));
        text1.setForeground(Color.WHITE);
        text1.setBounds(195,340,50,30);
        img4.add(text1);
        JLabel text2 =new JLabel("New PIN");
        text2.setFont(new Font("System",Font.BOLD,12));
        text2.setForeground(Color.WHITE);
        text2.setBounds(195,360,50,30);
        img4.add(text2);
        JTextField text4 =new JTextField();
        text4.setFont(new Font("System",Font.BOLD,12));
        text4.setBackground(Color.WHITE);
        text4.setForeground(Color.BLACK);
        text4.setBounds(255,340,100,30);
        img4.add(text1);
        JTextField text5 =new JTextField();
        text5.setFont(new Font("System",Font.BOLD,12));
        text5.setBackground(Color.WHITE);
        text5.setForeground(Color.BLACK);
        text5.setBounds(255,360,100,30);
        img4.add(text1);
        next6 =new JButton("Next");
        next6.setBounds(145,525,120,30);
        next6.addActionListener(this);
        img4.add(next6);
        exit6 =new JButton("Exit");
        exit6.setBounds(335,525,120,30);
        exit6.addActionListener(this);
        img4.add(exit6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit6){
//                System.exit(0);
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
