/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nanua
 */
public class Signup2 extends javax.swing.JFrame {

    /**
     * Creates new form Signup2
     */
    public Signup2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        anname = new javax.swing.JTextField();
        scn = new javax.swing.JRadioButton();
        scy = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        pnname = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        religion1 = new javax.swing.JComboBox<>();
        eqname = new javax.swing.JComboBox<>();
        income = new javax.swing.JComboBox<>();
        occupation = new javax.swing.JComboBox<>();
        ean = new javax.swing.JRadioButton();
        eay = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Page 2: Additional Details :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 390, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Income :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Religion :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Category :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Educational");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Occupation :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Pan number : ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Aadhaar number :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 160, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Senior citizen :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 160, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Existing account :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 160, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Qualification :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 30));

        anname.setBackground(new java.awt.Color(255, 255, 255));
        anname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anname.setForeground(new java.awt.Color(0, 0, 0));
        anname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(anname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 380, 30));

        scn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(scn);
        scn.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        scn.setForeground(new java.awt.Color(0, 0, 0));
        scn.setText("No");
        jPanel2.add(scn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        scy.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(scy);
        scy.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        scy.setForeground(new java.awt.Color(0, 0, 0));
        scy.setText("Yes");
        jPanel2.add(scy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 120, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Next->");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 140, 40));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\resourses\\iconall\\home1.png")); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, 70));

        pnname.setBackground(new java.awt.Color(255, 255, 255));
        pnname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnname.setForeground(new java.awt.Color(0, 0, 0));
        pnname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(pnname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 380, 30));

        category.setBackground(new java.awt.Color(255, 255, 255));
        category.setEditable(true);
        category.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        category.setForeground(new java.awt.Color(0, 0, 0));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "SC/ST", "Minority", "other-backward", "others" }));
        jPanel2.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 380, 30));

        religion1.setBackground(new java.awt.Color(255, 255, 255));
        religion1.setEditable(true);
        religion1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        religion1.setForeground(new java.awt.Color(0, 0, 0));
        religion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hindu", "Muslim", "Sikh", "Christian" }));
        jPanel2.add(religion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 380, 30));

        eqname.setBackground(new java.awt.Color(255, 255, 255));
        eqname.setEditable(true);
        eqname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        eqname.setForeground(new java.awt.Color(0, 0, 0));
        eqname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8th-9th standard", "high school", "intermadiate", "undergraduation", "graduate", "post gradute", "others" }));
        jPanel2.add(eqname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 380, 30));

        income.setBackground(new java.awt.Color(255, 255, 255));
        income.setEditable(true);
        income.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        income.setForeground(new java.awt.Color(0, 0, 0));
        income.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30000-50000", "50000-10000", "10000-50000", "50000-100000", "100000-500000", "500000-1000000", "1000000-others" }));
        jPanel2.add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 380, 30));

        occupation.setBackground(new java.awt.Color(255, 255, 255));
        occupation.setEditable(true);
        occupation.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        occupation.setForeground(new java.awt.Color(0, 0, 0));
        occupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "private-job", "government-job", "aided-job", "labour-work", "others" }));
        jPanel2.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 380, 30));

        ean.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(ean);
        ean.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        ean.setForeground(new java.awt.Color(0, 0, 0));
        ean.setText("No");
        jPanel2.add(ean, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        eay.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(eay);
        eay.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        eay.setForeground(new java.awt.Color(0, 0, 0));
        eay.setText("Yes");
        jPanel2.add(eay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<-Previous");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int identity=0;
    int getId(){
        ResultSet rs=null;
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            String sql="select max(id) from sigup1";
            Statement st=con.createStatement();
            
            rs=st.executeQuery(sql);
            while(rs.next()){
                identity=rs.getInt(1);
                identity++;    
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    return identity;
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        validation();
        if(validation()){
            insertData();
            sign_in();
        }
        else{
            JOptionPane.showMessageDialog(this, "Validation issues");
    }      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pnname.setText("");
        anname.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Signup1 s2=new Signup1();
        s2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    String adhar,pan,Religion,Category,Income,Education,Occupation,Senior,Existing;
    boolean validation(){
        Religion=(String)religion1.getSelectedItem();
        Category=(String)category.getSelectedItem();
        Income=(String)income.getSelectedItem();
        Education=(String)eqname.getSelectedItem();
        Occupation=(String)occupation.getSelectedItem();
        pan=pnname.getText();
        adhar=anname.getText();
          if(pan.equals("")||adhar.equals("")){ 
            JOptionPane.showMessageDialog(this, "Provide complete information..");
            return false;
        }
        return true;
        
    }
    String senior(){
        String Senior=null;
        if(scy.isSelected()){
          Senior="Senior citizen";
        }else if(scn.isSelected()){
          Senior="Not a senior citizen";
        }
        return Senior;
    }
    String exist(){
        String Existing=null;
        if(eay.isSelected()){
          Existing="Existing account";
        }else if(ean.isSelected()){
          Existing="Not a existing account";
        }
        return Existing;   
    }

    void insertData(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            
            String sql ="insert into sigup1 values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1, getId());
            st.setString(2, Religion);
            st.setString(3, Category);
            st.setString(4, Income);
            st.setString(5, Education);
            st.setString(6, Occupation);
            st.setString(7, pan);
            st.setString(8, adhar);
            st.setString(9, senior());
            st.setString(10, exist());
            int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this,"Record inserted successfully");
            }
            else{
                JOptionPane.showMessageDialog(this,"Record  not inserted successfully");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
   
    void sign_in(){
        Signupaccounttype s2=new Signupaccounttype();
        s2.setVisible(true);
        this.dispose();
        s2.showdetails();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JRadioButton ean;
    private javax.swing.JRadioButton eay;
    private javax.swing.JComboBox<String> eqname;
    private javax.swing.JComboBox<String> income;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> occupation;
    private javax.swing.JTextField pnname;
    private javax.swing.JComboBox<String> religion1;
    private javax.swing.JRadioButton scn;
    private javax.swing.JRadioButton scy;
    // End of variables declaration//GEN-END:variables
}
