/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author nanua
 */
public class Signupaccounttype extends javax.swing.JFrame {

    /**
     * Creates new form Signupaccounttype
     */
    public Signupaccounttype() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sa = new javax.swing.JRadioButton();
        ca = new javax.swing.JRadioButton();
        fda = new javax.swing.JRadioButton();
        rda = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        es = new javax.swing.JCheckBox();
        email = new javax.swing.JCheckBox();
        mobile = new javax.swing.JCheckBox();
        atmcard = new javax.swing.JCheckBox();
        internet = new javax.swing.JCheckBox();
        cheque = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        pinno = new javax.swing.JLabel();
        cardno = new javax.swing.JLabel();
        declare = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("<-Previous");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 140, 40));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Next ->");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 130, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 690, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 690, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Page 3 : Account Details :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 390, 50));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Services Required :");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 220, 30));

        sa.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sa);
        sa.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        sa.setForeground(new java.awt.Color(0, 0, 0));
        sa.setText("Saving Account");
        jPanel5.add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        ca.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(ca);
        ca.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        ca.setForeground(new java.awt.Color(0, 0, 0));
        ca.setText("Current Account");
        jPanel5.add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        fda.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fda);
        fda.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        fda.setForeground(new java.awt.Color(0, 0, 0));
        fda.setText("Fixed Deposit Account");
        jPanel5.add(fda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        rda.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rda);
        rda.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rda.setForeground(new java.awt.Color(0, 0, 0));
        rda.setText("Recurring Deposit Account");
        jPanel5.add(rda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Account Type :");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("PIN :");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 160, 30));

        es.setBackground(new java.awt.Color(255, 255, 255));
        es.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        es.setForeground(new java.awt.Color(0, 0, 0));
        es.setText("E-Statements");
        jPanel5.add(es, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 150, 30));

        email.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(email);
        email.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setText("Email Alerts");
        jPanel5.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 150, 30));

        mobile.setBackground(new java.awt.Color(255, 255, 255));
        mobile.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        mobile.setForeground(new java.awt.Color(0, 0, 0));
        mobile.setText("Mobile Banking");
        jPanel5.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 150, 30));

        atmcard.setBackground(new java.awt.Color(255, 255, 255));
        atmcard.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        atmcard.setForeground(new java.awt.Color(0, 0, 0));
        atmcard.setText("ATM CARD");
        jPanel5.add(atmcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 150, 30));

        internet.setBackground(new java.awt.Color(255, 255, 255));
        internet.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        internet.setForeground(new java.awt.Color(0, 0, 0));
        internet.setText("Internet Banking");
        jPanel5.add(internet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 150, 30));

        cheque.setBackground(new java.awt.Color(255, 255, 255));
        cheque.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cheque.setForeground(new java.awt.Color(0, 0, 0));
        cheque.setText("Cheque-book");
        jPanel5.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 150, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Card Number :");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 30));

        pinno.setBackground(new java.awt.Color(255, 255, 255));
        pinno.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        pinno.setForeground(new java.awt.Color(0, 0, 0));
        pinno.setText("XXXX");
        jPanel5.add(pinno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 290, 30));

        cardno.setBackground(new java.awt.Color(255, 255, 255));
        cardno.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        cardno.setForeground(new java.awt.Color(0, 0, 0));
        cardno.setText("XXXX-XXXX-XXXX-ABCD");
        jPanel5.add(cardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 290, 30));

        declare.setBackground(new java.awt.Color(255, 255, 255));
        declare.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        declare.setForeground(new java.awt.Color(0, 0, 0));
        declare.setText("I hereby declares that the above entered details correct to the best of my knowledge");
        jPanel5.add(declare, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 500, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("It would appear in ATM-Card , ChequeBook and Statements");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 330, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("(Your 14-digits Card number:)");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 210, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("(4-digits password)");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 210, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 690, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String accounttype(){
        String account="";
        if(sa.isSelected()){
          account="Saving Account";
        }else if(ca.isSelected()){
          account="Current Account";
        }else if(fda.isSelected()){
          account="Fixed Deposit Account";
        }else if(rda.isSelected()){
          account="Recurring Deposit Account";
        }
        return account;
    }
    int identity=0;
    int getId(){
        ResultSet rs=null;
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            String sql="select max(id) from signupaccount";
            Statement st=con.createStatement();
            
            rs=st.executeQuery(sql);
            while(rs.next()){
                identity=rs.getInt(1);
                identity++;    
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    return identity;
    }
    Random r1=new Random();
    int Card(){
        retreivec();
        int k,a1,a2;
            k=Integer.parseInt(anname);
            a1=k/100000000;
            a2=k%100000000;
//        long cardnumber=Math.abs(r1.nextLong()%90000000L)+51040905000000000L
        int cardnumber=(a1*10000)+a2;
        return (int) cardnumber;
    }
    int Pin(){
//        long pinnumber=Math.abs(r1.nextLong()%90000000L)+51040905000000000L;
        int pinnumber=2005;
        return (int) pinnumber;
    }
    String dob,mnname,pnname,anname;
    void retreivec(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            String sql1 = "SELECT * FROM signup WHERE id = (SELECT MAX(id) FROM signup)";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            ResultSet rs1 = pst1.executeQuery();

            if (rs1.next()) {
            mnname=rs1.getString("mobile");
              }
            String sql2 = "SELECT * FROM sigup1 WHERE id = (SELECT MAX(id) FROM sigup1)";
            PreparedStatement pst2 = con.prepareStatement(sql2);
            ResultSet rs2 = pst2.executeQuery();

            if (rs2.next()) {
            pnname=rs2.getString("pan");
            anname=rs2.getString("adhar");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    void showdetails(){    
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            String sql3 = "SELECT * FROM signupaccount WHERE id = (SELECT MAX(id) FROM signupaccount)";
            PreparedStatement pst3 = con.prepareStatement(sql3);
            ResultSet rs3 = pst3.executeQuery();

            if (rs3.next()) {
                String card11=rs3.getString("card");
                String card12=rs3.getString("pin");
            cardno.setText(card11);
            pinno.setText(card12);
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    }
    String Services(){
        String services="";
        if(atmcard.isSelected()){
            services="Atm-Card ,";
        }if(cheque.isSelected()){
            services=services+"Cheque-Book ,";
        }if(email.isSelected()){
            services=services+"Email-Address ,";
        }if(mobile.isSelected()){
            services=services+"Mobile-Banking ,";
        }if(internet.isSelected()){
            services=services+"Internet-Banking ,";
        }
        if(es.isSelected()){
            services=services+"E-Statemants";
        }
        return services;
    }
    int insertData(int cardnumber,int pinnumber){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            
            String sql ="insert into signupaccount values (?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1, getId());
            st.setInt(2, Card());
            st.setInt(3, Pin());
            st.setString(4, Services());
            st.setString(5, accounttype());
            int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this," Record inserted successfully");  
            }
            else{
                JOptionPane.showMessageDialog(this,"Record  not inserted successfully");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return 0;
    }
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here
        Signup2 s2=new Signup2();
        s2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here: 
        if(declare.isSelected()){
        insertData(Card(),Pin());
        Signup3 s2=new Signup3();
        s2.setVisible(true);
        this.dispose();
        s2.showdetails();
        }else{
            JOptionPane.showMessageDialog(this,"select checkbox..");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signupaccounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signupaccounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signupaccounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signupaccounttype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signupaccounttype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox atmcard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton ca;
    private javax.swing.JLabel cardno;
    private javax.swing.JCheckBox cheque;
    private javax.swing.JCheckBox declare;
    private javax.swing.JCheckBox email;
    private javax.swing.JCheckBox es;
    private javax.swing.JRadioButton fda;
    private javax.swing.JCheckBox internet;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JCheckBox mobile;
    private javax.swing.JLabel pinno;
    private javax.swing.JRadioButton rda;
    private javax.swing.JRadioButton sa;
    // End of variables declaration//GEN-END:variables
}
