/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nanua
 */
public class Signup1 extends javax.swing.JFrame {

    /**
     * Creates new form Signup1
     */
    public Signup1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        formno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        othersms = new javax.swing.JRadioButton();
        married = new javax.swing.JRadioButton();
        unmarried = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        eaname = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        pcname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        othersg = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mnname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        formno.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(formno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 110, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Date of Birth :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Father's Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gender :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Martial Status :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Address :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("City :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Pin code  :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 100, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("State :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Email Address :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 380, 30));

        cname.setBackground(new java.awt.Color(255, 255, 255));
        cname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cname.setForeground(new java.awt.Color(0, 0, 0));
        cname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 380, 30));

        othersms.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(othersms);
        othersms.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        othersms.setForeground(new java.awt.Color(0, 0, 0));
        othersms.setText("Others");
        jPanel1.add(othersms, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        married.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(married);
        married.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        married.setForeground(new java.awt.Color(0, 0, 0));
        married.setText("Married");
        jPanel1.add(married, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        unmarried.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(unmarried);
        unmarried.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        unmarried.setForeground(new java.awt.Color(0, 0, 0));
        unmarried.setText("Unmarried");
        unmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unmarriedActionPerformed(evt);
            }
        });
        jPanel1.add(unmarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 140, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 140, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\resourses\\iconall\\home1.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, 70));

        fname.setBackground(new java.awt.Color(255, 255, 255));
        fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 0));
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 380, 30));

        eaname.setBackground(new java.awt.Color(255, 255, 255));
        eaname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eaname.setForeground(new java.awt.Color(0, 0, 0));
        eaname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(eaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 380, 30));

        aname.setBackground(new java.awt.Color(255, 255, 255));
        aname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aname.setForeground(new java.awt.Color(0, 0, 0));
        aname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 380, 30));

        sname.setBackground(new java.awt.Color(255, 255, 255));
        sname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sname.setForeground(new java.awt.Color(0, 0, 0));
        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 380, 30));

        pcname.setBackground(new java.awt.Color(255, 255, 255));
        pcname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pcname.setForeground(new java.awt.Color(0, 0, 0));
        pcname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(pcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 380, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Application form : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 310, 50));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jDateChooser1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 380, 30));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(0, 0, 0));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(0, 0, 0));
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        othersg.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(othersg);
        othersg.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        othersg.setForeground(new java.awt.Color(0, 0, 0));
        othersg.setText("Others");
        jPanel1.add(othersg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Page 1: Customer Details :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 390, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Mobile No.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 100, 30));

        mnname.setBackground(new java.awt.Color(255, 255, 255));
        mnname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnname.setForeground(new java.awt.Color(0, 0, 0));
        mnname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(mnname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 380, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int identity=0;
    int getId(){
        ResultSet rs=null;
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
            String sql="select max(id) from signup";
            Statement st=con.createStatement();
            
            rs=st.executeQuery(sql);
            while(rs.next()){
                identity=rs.getInt(1);
                String iden=rs.getString(1);
                formno.setText(iden);
                identity++;    
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
    return identity;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        validation();
        if(validation()){
            insertData();
            sign_in();
        }
        else{
            JOptionPane.showMessageDialog(this, "Validation issues");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        fname.setText("");
        eaname.setText("");
        aname.setText("");
        cname.setText("");
        pcname.setText("");
        sname.setText("");
        mnname.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void unmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unmarriedActionPerformed
    String Name,dob,Fname,EAname,Aname,Cname,PCname,Sname,MNname;
    String gend(){
        String gender=null;
        if(male.isSelected()){
          gender="Male";
        }else if(female.isSelected()){
        gender="Female";
        }
        else if(othersg.isSelected()){
        gender="Others";
        }
        return gender;
    }
    String mart(){
        String martial_status=null;
        if(married.isSelected()){
          martial_status="Married";
        }else if(unmarried.isSelected()){
        martial_status="Unmarried";
        }
        else if(othersms.isSelected()){
        martial_status="Others";
        }
        return martial_status;
    }

    boolean validation(){
        Name=name.getText();
        dob=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(); 
        Fname=fname.getText();
        EAname=eaname.getText();
        Aname=aname.getText();
        Cname=cname.getText();
        PCname=pcname.getText();
        Sname=sname.getText();
        MNname=mnname.getText();
        if(Name.equals("") ||Fname.equals("")||EAname.equals("")||Aname.equals("")||Cname.equals("")||PCname.equals("")||Sname.equals("")||MNname.equals("")){
            JOptionPane.showMessageDialog(this, "Provide complete information..");
            return false;
        }
        return true;
    }
    void insertData(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/simplebankingsystem?zeroDateTimeBehavior=CONVERT_TO_NULL";
            
            Connection con=DriverManager.getConnection(url,"root","Adity@25062005");
    
            String sql ="insert into signup values (?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1, getId());
            st.setString(2, Name);
            st.setString(3, Fname);
            st.setString(4, dob);
            st.setString(5,gend());
            st.setString(6, EAname);
            st.setString(7,mart());
            st.setString(8, Aname);
            st.setString(9, Cname);
            st.setString(10, PCname);
            st.setString(11, Sname);
            st.setString(12, MNname);
            
         
            int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this,"Record inserted successfully");
            }
            else{
                JOptionPane.showMessageDialog(this,"Record  not inserted successfully");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
   
    void sign_in(){
        Signup2 s2=new Signup2();
        s2.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup1().setVisible(true);
            }
        });
    }
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField eaname;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel formno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton married;
    private javax.swing.JTextField mnname;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton othersg;
    private javax.swing.JRadioButton othersms;
    private javax.swing.JTextField pcname;
    private javax.swing.JTextField sname;
    private javax.swing.JRadioButton unmarried;
    // End of variables declaration//GEN-END:variables

}
