/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;


/**
 *
 * @author nanua
 */
public class Transaction extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
    }
    JButton balance,mini,cash_withdrawl,pin_change,fast_cash,deposit,exit;
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 0));
        setSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 810));
        JLabel text =new JLabel("Please select your Transaction:");
        text.setFont(new Font("System",Font.BOLD,24));
        text.setForeground(Color.WHITE);
        text.setBounds(255,310,400,30);
        img.add(text);
        deposit =new JButton("Deposit");
        deposit.setBounds(195,370,125,35);
        deposit.addActionListener(this);
        img.add(deposit);
        fast_cash =new JButton("Fast Cash");
        fast_cash.setBounds(195,420,125,35);
        fast_cash.addActionListener(this);
        img.add(fast_cash);
        pin_change =new JButton("Pin Change");
        pin_change.setBounds(195,470,125,35);
        pin_change.addActionListener(this);
        img.add(pin_change);
        cash_withdrawl =new JButton("Cash Withdrawl");
        cash_withdrawl.setBounds(565,370,125,35);
        cash_withdrawl.addActionListener(this);
        img.add(cash_withdrawl);
        mini =new JButton("Mini Statements");
        mini.setBounds(565,420,125,35);
        mini.addActionListener(this);
        img.add(mini);
        balance =new JButton("Balance Enquiry");
        balance.setBounds(565,470,125,35);
        balance.addActionListener(this);
        img.add(balance);
        exit =new JButton("Exit");
        exit.setBounds(565,520,125,35);
        exit.addActionListener(this);
        img.add(exit);

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    /**
     * @param args the command line arguments
     */
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit){
                Login l1=new Login();
                l1.setVisible(true);
                this.dispose();
            }else if(ae.getSource()==deposit){
                Deposit d1=new Deposit();
                d1.setVisible(true);
                this.dispose();
            }else if(ae.getSource()==cash_withdrawl){
                CashWithdrawl cw1=new CashWithdrawl();
                cw1.setVisible(true);
                this.dispose();
             
            }else if(ae.getSource()==pin_change){
                PinChange pc=new PinChange();
                pc.setVisible(true);
                this.dispose();
            }
            else if(ae.getSource()==mini){
                Mini_Statement ms=new Mini_Statement();
                ms.setVisible(true);
                this.dispose();
            }
            else if(ae.getSource()==fast_cash){
                FastCash fc =new FastCash();
                fc.setVisible(true);
                this.dispose();
            }
            else if(ae.getSource()==balance){
                Balance_Enquiry be=new Balance_Enquiry();
                be.setVisible(true);
                this.dispose();
            }
        }

         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
